
import java.awt.Color;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author mrosrom2904
 */
public class ventana1 extends javax.swing.JFrame {

    String numero1 = null;
    String numero2 = null;
    String operando = "";
    String resultado = "";
    boolean decimales = false;
    JButton ultPulsado;

    /**
     * Creates new form ventana1
     */
    public ventana1() {
        initComponents();

//        this.getContentPane().setBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        dividido = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        pantalla = new javax.swing.JTextField();
        historial = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 102, 153));
        setResizable(false);

        uno.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        uno.setText("1");
        uno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        dos.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        dos.setText("2");
        dos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        tres.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        tres.setText("3");
        tres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        cuatro.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        cuatro.setText("4");
        cuatro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        cinco.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        cinco.setText("5");
        cinco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        seis.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        seis.setText("6");
        seis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        siete.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        siete.setText("7");
        siete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });

        ocho.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        ocho.setText("8");
        ocho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        nueve.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        nueve.setText("9");
        nueve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });

        cero.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        cero.setText("0");
        cero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        decimal.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        decimal.setText(".");
        decimal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });

        limpiar.setBackground(new java.awt.Color(255, 0, 51));
        limpiar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        limpiar.setForeground(new java.awt.Color(255, 255, 255));
        limpiar.setText("C");
        limpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        menos.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        menos.setText("-");
        menos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        dividido.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        dividido.setText("/");
        dividido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dividido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divididoActionPerformed(evt);
            }
        });

        multiplicar.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        multiplicar.setText("x");
        multiplicar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });

        igual.setBackground(new java.awt.Color(0, 153, 153));
        igual.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        igual.setForeground(new java.awt.Color(255, 255, 255));
        igual.setText("=");
        igual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        mas.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        mas.setText("+");
        mas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });

        pantalla.setEditable(false);
        pantalla.setBackground(new java.awt.Color(255, 255, 255));
        pantalla.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N

        historial.setText(" ");
        historial.setToolTipText("");
        historial.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        borrar.setBackground(new java.awt.Color(255, 204, 102));
        borrar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        borrar.setForeground(new java.awt.Color(255, 255, 255));
        borrar.setText("<-");
        borrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pantalla)
                    .addComponent(historial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(siete)
                                    .addComponent(cuatro)
                                    .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cinco, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ocho, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nueve, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(seis, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(decimal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(igual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mas, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dividido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))))))
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cinco, cuatro, dividido, dos, menos, multiplicar, nueve, ocho, seis, siete, tres, uno});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historial, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uno, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(dos, javax.swing.GroupLayout.Alignment.CENTER))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuatro, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(cinco, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(seis, javax.swing.GroupLayout.Alignment.CENTER))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(siete)
                            .addComponent(ocho)
                            .addComponent(nueve))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dividido)
                                    .addComponent(multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(decimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cinco, cuatro, dividido, dos, menos, multiplicar, nueve, ocho, seis, siete, tres, uno});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String borrarNumero (String cadena) {
        if (cadena == null || cadena.length() == 0) {
            return cadena;
        }
        return cadena.substring(0, cadena.length() - 1);
    }
    
    private void pulsaNumero(JButton boton) {
        if (!resultado.isEmpty()) {
            numero1 = pantalla.getText();
            resultado = "";
            numero2 = null;
            pantalla.setText("");
        }
        ultPulsado = boton;
    }

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        pulsaNumero(uno);
        pantalla.setText(pantalla.getText() + "1");
        historial.setText(historial.getText() + "1");
    }//GEN-LAST:event_unoActionPerformed


    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        pulsaNumero(dos);
        pantalla.setText(pantalla.getText() + "2");
        historial.setText(historial.getText() + "2");
    }//GEN-LAST:event_dosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        pulsaNumero(tres);
        pantalla.setText(pantalla.getText() + "3");
        historial.setText(historial.getText() + "3");
    }//GEN-LAST:event_tresActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        pulsaNumero(cuatro);
        pantalla.setText(pantalla.getText() + "4");
        historial.setText(historial.getText() + "4");
    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        pulsaNumero(cinco);
        pantalla.setText(pantalla.getText() + "5");
        historial.setText(historial.getText() + "5");
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        pulsaNumero(seis);
        pantalla.setText(pantalla.getText() + "6");
        historial.setText(historial.getText() + "6");
    }//GEN-LAST:event_seisActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        pulsaNumero(siete);
        pantalla.setText(pantalla.getText() + "7");
        historial.setText(historial.getText() + "7");
    }//GEN-LAST:event_sieteActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        pulsaNumero(ocho);
        pantalla.setText(pantalla.getText() + "8");
        historial.setText(historial.getText() + "8");
    }//GEN-LAST:event_ochoActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        pulsaNumero(nueve);
        pantalla.setText(pantalla.getText() + "9");
        historial.setText(historial.getText() + "9");
    }//GEN-LAST:event_nueveActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        pulsaNumero(cero);
        pantalla.setText(pantalla.getText() + "0");
        historial.setText(historial.getText() + "0");
    }//GEN-LAST:event_ceroActionPerformed

    private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
        if (!decimales && !"".equals(pantalla.getText())) {
            pantalla.setText(pantalla.getText() + ".");
            decimales = true;
            historial.setText(historial.getText() + ".");
        }
        ultPulsado = decimal;
    }//GEN-LAST:event_decimalActionPerformed



    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        numero1 = null;
        numero2 = null;
        resultado = "";
        decimales = false;
        operando = "";
        pantalla.setText("");
        historial.setText("");
        ultPulsado = null;
    }//GEN-LAST:event_limpiarActionPerformed

    private String operar(String num1, String num2, String simbolo) {
        double n1 = Double.parseDouble(num1);
        double n2 = Double.parseDouble(num2);

        String res = "";
        switch (simbolo) {
            case "+" ->
                res = String.valueOf(n1 + n2);
            case "-" ->
                res = String.valueOf(n1 - n2);
            case "*" ->
                res = String.valueOf(n1 * n2);
            case "/" ->
                res = String.valueOf(n1 / n2);
        }
        return res;
    }


    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        decimales = false;
        if (!"".equals(pantalla.getText()) && !"-".equals(pantalla.getText()) && numero1 == null && ultPulsado != menos) {
            numero1 = pantalla.getText();
            operando = "-";
            pantalla.setText("");
            historial.setText(historial.getText() + "-");
        }
        if (!"".equals(pantalla.getText()) && !"-".equals(pantalla.getText())
                && numero1 != null && ultPulsado != menos && ultPulsado != dividido
                && ultPulsado != mas && ultPulsado != multiplicar) {
            numero2 = pantalla.getText();
            resultado = operar(numero1, numero2, operando);
            pantalla.setText(resultado);
            historial.setText(resultado + operando);
            operando = "-";
            numero1 = resultado;
            numero2 = null;
            ultPulsado = menos;
        }

        // para numeros negativos
        if ("".equals(pantalla.getText()) && ultPulsado != menos && numero1 == null) {
            pantalla.setText("-");
            historial.setText("-");
            ultPulsado = menos;
        }

    }//GEN-LAST:event_menosActionPerformed

    private void divididoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divididoActionPerformed
        decimales = false;
        if (!"".equals(pantalla.getText()) && !"-".equals(pantalla.getText()) && numero1 == null) {
            numero1 = pantalla.getText();
            operando = "/";
            pantalla.setText("");
            historial.setText(historial.getText() + "/");
        }
        if (!"".equals(pantalla.getText()) && !"-".equals(pantalla.getText()) && numero1 != null
                && ultPulsado != dividido && ultPulsado != mas && ultPulsado != multiplicar) {
            numero2 = pantalla.getText();
            resultado = operar(numero1, numero2, operando);
            pantalla.setText(resultado);
            historial.setText(resultado + operando);
            operando = "/";
            numero1 = resultado;
            numero2 = null;
            ultPulsado = dividido;
        }
    }//GEN-LAST:event_divididoActionPerformed

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarActionPerformed
        decimales = false;
        if (!"".equals(pantalla.getText()) && !"-".equals(pantalla.getText()) && numero1 == null) {
            numero1 = pantalla.getText();
            operando = "*";
            pantalla.setText("");
            historial.setText(historial.getText() + "*");
        }
        if (!"".equals(pantalla.getText()) && !"-".equals(pantalla.getText()) && numero1 != null
                && ultPulsado != mas && ultPulsado != multiplicar && ultPulsado != dividido) {
            numero2 = pantalla.getText();
            resultado = operar(numero1, numero2, operando);
            pantalla.setText(resultado);
            historial.setText(resultado + operando);
            operando = "*";
            numero1 = resultado;
            numero2 = null;
            ultPulsado = multiplicar;
        }
    }//GEN-LAST:event_multiplicarActionPerformed


    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        if (!"".equals(pantalla.getText()) && !"-".equals(pantalla.getText()) && numero1 != null && numero2 == null) {
            numero2 = pantalla.getText();
            resultado = operar(numero1, numero2, operando);
            pantalla.setText(resultado);
            historial.setText(" ");

            ultPulsado = igual;
            operando = "";
            decimales = false;
            numero1 = null;
            numero2 = null;
        }
    }//GEN-LAST:event_igualActionPerformed


    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        decimales = false;
        if (!"".equals(pantalla.getText()) && !"-".equals(pantalla.getText()) && numero1 == null) {
            numero1 = pantalla.getText();
            operando = "+";
            pantalla.setText("");
            historial.setText(historial.getText() + "+");
        }
        if (!"".equals(pantalla.getText()) && !"-".equals(pantalla.getText()) && numero1 != null && ultPulsado != mas
                && ultPulsado != multiplicar && ultPulsado != dividido) {
            numero2 = pantalla.getText();
            resultado = operar(numero1, numero2, operando);
            pantalla.setText(resultado);
            operando = "+";
            historial.setText(resultado + operando);
            numero1 = resultado;
            numero2 = null;
            ultPulsado = mas;
        }

    }//GEN-LAST:event_masActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        pantalla.setText(borrarNumero(pantalla.getText()));
        historial.setText(borrarNumero(historial.getText()));
    }//GEN-LAST:event_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton decimal;
    private javax.swing.JButton dividido;
    private javax.swing.JButton dos;
    private javax.swing.JLabel historial;
    private javax.swing.JButton igual;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    private javax.swing.JButton multiplicar;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JTextField pantalla;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
